### ISSUE TITLE
update needed?

### ISSUE THREAD

**Issue by shayo** [rdelrosario/xamarin-plugins#113]
Trying to add this to a recent project failed.
Update needed?

Attempting to resolve dependencies for package 'Xam.Plugin.PushNotification.1.2.4' with DependencyBehavior 'Lowest'
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'Xamarin.Forms 2.3.3.193 constraint: Xamarin.Android.Support.v4 (= 23.3.0)', 'Xamarin.Forms 2.3.3.193 constraint: Xamarin.Android.Support.Design (= 23.3.0)', 'Xamarin.Forms 2.3.3.193 constraint: Xamarin.Android.Support.v7.AppCompat (= 23.3.0)', 'Xamarin.Forms 2.3.3.193 constraint: Xamarin.Android.Support.v7.CardView (= 23.3.0)', 'Xamarin.Forms 2.3.3.193 constraint: Xamarin.Android.Support.v7.MediaRouter (= 23.3.0)'
Unable to resolve dependencies. 'Xamarin.Android.Support.Design 25.1.1' is not compatible with 'Xamarin.Forms 2.3.3.193 constraint: Xamarin.Android.Support.Design (= 23.3.0)'.

**Comment by shayo** [comment]
Trying to compile results with the following error:

/Users/shayo/Projects/ClimbTag/PushNotification/PushNotification/PushNotification.Plugin.Android/PushNotificationGcmListener.cs(33,33): Error CS1061: Type `Android.App.PendingIntent' does not contain a definition for `SetAction' and no extension method `SetAction' of type `Android.App.PendingIntent' could be found. Are you missing an assembly reference? (CS1061) (PushNotification.Plugin.Android)

            PendingIntent resultPendingIntent = PendingIntent.GetActivity(context, pendingIntentId, resultIntent, PendingIntentFlags.OneShot | PendingIntentFlags.UpdateCurrent );
            resultPendingIntent.SetAction($"{currentMillis}");

**Comment by rdelrosario** [comment]
Should be fixed on https://www.nuget.org/packages/Xam.Plugin.PushNotification/1.2.5-beta
