### ISSUE TITLE
Crashing app when used crossPushNotification.Current.Register();

### ISSUE THREAD

**Issue by hussamalzahabi** [rdelrosario/xamarin-plugins#123]
Hi Every one ,

i have problem after complete configure this package rdelrosario/xamarin-plugins .

firstly i created the fire-base account and get the sender in order to put in initialize ( main ) 
after this process i invoked the crossPushNotification.Current.Register(); on app cs ( overriding onstart

but when run the project on the emulator it didn't work ( make crashing ) and i didn't receive any msg from fire-base i think this package's its lack to many point should be illustrated

**Comment by benevbright** [comment]
Basically you need to test it on the Release build with real smartphone.

**Comment by hussamalzahabi** [comment]
so if i used a real smartphone in release mode should receive a notification from fire base ?

**Comment by benevbright** [comment]
If you did everything correctly, yes.

**Comment by hussamalzahabi** [comment]
yes i update this package to beta mode and im using api 25 ( 7.1 nuget )
and the question should update the XF to last one ?

**Comment by benevbright** [comment]
At least I'm using lastest stable one. (Not pre release)

**Comment by hussamalzahabi** [comment]
this package require backend stuff ?? or not ?

**Comment by hussamalzahabi** [comment]
its working correctly :) because i used a real one

**Comment by benevbright** [comment]
Good to hear that!
