### ISSUE TITLE
Getting DLL Error

### ISSUE THREAD

**Issue by vbisbest** [rdelrosario/xamarin-plugins#14]
Using latest everything getting an error loading project:
 Error XA0009: Error while loading assembly: /Users/ray/Projects/MyApp/packages/Xam.Plugin.LocalNotifications.1.0.0.0/lib/portable-net45+wp8+wpa81+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10/LocalNotifications.Plugin.Abstractions.dll (XA0009)

**Comment by rdelrosario** [comment]
Did you try clean already on the projects?

**Comment by rdelrosario** [comment]
This is not an error of this plugin is making reference to LocalNotification Plugin (Xam.Plugin.LocalNotifications)
