### ISSUE TITLE
Change Dependencies to just use requierd packages 

### ISSUE THREAD

**Issue by jorgenstorlie** [rdelrosario/xamarin-plugins#16]
Now it require Xamarin.GooglePlayServices, the lates version is very big

It may be better to just use requierd packages:
http://redth.codes/Xamarin-Google-Play-Services-Improvements/

**Comment by rdelrosario** [comment]
Thanks for the suggestion. Just changed the depencies and updated the Android implementation.

https://www.nuget.org/packages/Xam.Plugin.PushNotification/

**Comment by jorgenstorlie** [comment]
Is anything else changed?

This code does not work anymore:

CrossPushNotification.Current.Register ();

(the app is 5 mb smaler now)

**Comment by rdelrosario** [comment]
What issues are you having?

Are you getting the token?

**Comment by jorgenstorlie** [comment]
Then I compile I get this error on the code:
CrossPushNotification.Current.Register ();

Error CS0103: The name `CrossPushNotification' does not exist in the current context (CS0103) (Contendo.Android)

Using this:
using PushNotification.Plugin;

**Comment by rdelrosario** [comment]
Weird. I tested this before releasing. Try removing the package , adding it
again and cleaning the solution.

**Comment by jorgenstorlie** [comment]
I have done this a couple of times

The class
public class  CrossPushNotificationListener : IPushNotificationListener
compiles so something is working

**Comment by rdelrosario** [comment]
Try the newest version of the package just published. Let me know if now works

**Comment by jorgenstorlie** [comment]
Succes
