### ISSUE TITLE
Init not working under iOS

### ISSUE THREAD

**Issue by ThomasKIT** [rdelrosario/xamarin-plugins#17]
I am successfully using the plugin on Android, but with iOS it fails during initilization.

iOS 8.4:
Should initialize before use on FinishedLaunching method of AppDelegate class. Example:  CrossPushNotification.Initialize<CrossPushNotificationListener>()

iOS 7.1:
UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread.

Last point of entry before the exceptions occur: CrossPushNotification.Current.Register()

This is my AppDelegate FinishedLaunching:

```
    public override bool FinishedLaunching(UIApplication app, NSDictionary options)
    {
        global::Xamarin.Forms.Forms.Init();

        CrossPushNotification.Initialize<CrossPushNotificationListener>();

        InitXLabsServices();
        ImageCircleRenderer.Init();
        LoadApplication(new KinsmenApp());

        return base.FinishedLaunching(app, options);
    }
```

Of course I did set up the Provisioning Profile and Push Notification Permission at the Developer Center.

How can I get more information about where it actually crashes inside the plugin?

Edit:
I took a look at the plugin's source code and after using the following three lines directly it registered successfully, but this way I am not using the Plugin:

```
  UIUserNotificationType userNotificationTypes = UIUserNotificationType.Alert | UIUserNotificationType.Badge | UIUserNotificationType.Sound;
  UIUserNotificationSettings settings = UIUserNotificationSettings.GetSettingsForTypes(userNotificationTypes, null);
  UIApplication.SharedApplication.RegisterUserNotificationSettings(settings);
```

Could it be possible that the preprocessor directives aren't getting handled properly and therefore the wrong code gets executed?
# if **IOS**

**Comment by rdelrosario** [comment]
You should initialize the plugin after the LoadApplication call.

**Comment by ThomasKIT** [comment]
That leads to

```
  UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread.
```

**Comment by rdelrosario** [comment]
Can you send the code where you are calling the register method?
