### ISSUE TITLE
Windows Phone Support

### ISSUE THREAD

**Issue by michaelsync** [rdelrosario/xamarin-plugins#22]
Hi guys (cc @rdelrosario)

Thanks for creating this amazing plugin.. 

I understand that windows phone supports is still on pipeline. but I like to ask some questions at early stage so we will understand whats coming up for Windows Phone. 
1. I found PushNotification.Plugin.WindowsPhone8, PushNotification.Plugin.WindowsPhone81 and PushNotification.Plugin.WindowsStore folders. Are you planning to implement for each version? Is "PushNotification.Plugin.WindowsStore" the universal app? As the universal app supports both Windows Phone 8.1 and Windows 10, you guys may not even have the different implementation. 
2.  Do you guys use Azure Mobile server or Notification Hub? I haven't really looked at the implementation for this plugin yet but I assume that this plugin will help the app to talk directly to GCM or Apple Notification service. What about if we use Azure Notification Hub as the middle man so the app can talk to Azure Notification Hub (one implementation) and then NotificationHub will talk to GCM or Apple or etc? 

Thanks!

**Comment by rdelrosario** [comment]
Hi @michaelsync 
1. About windows haven't had time to implement that yet looking for some collaboration in that part, but sure might go with the universal app support.
2. Haven't use Azure Mobile Server or Notification Hub, but might look into it if is a viable option to improve the plugin.

Best Regards,

Rendy Del Rosario

**Comment by rdelrosario** [comment]
Btw, I'm not familiar with windows development so i'm open to any help i can get so if you want to collaborate will be great!

Thanks for your comments

**Comment by michaelsync** [comment]
@rdelrosario I am familiar with windows development but am still new to xamarin. :-) ya I am interested to help with windows part. I will fork the repo and will get myself familiar with xamarin and your plugin first. and then will inform you.. Thanks!
