### ISSUE TITLE
Pushnotification doesn't show a popup Android

### ISSUE THREAD

**Issue by SamVanCutsem** [rdelrosario/xamarin-plugins#26]
Hi, I have implemented your library in my Android project. When my device receives a notification it show in the notification center but doesn't give a popup. Any idea how to fix this?

**Comment by rdelrosario** [comment]
Hi

Not sure what you mean with the popup. Do you have any examples?

The plugin basically is just to receive the notification message and also
supports to show it on notification center.

**Comment by SamVanCutsem** [comment]
When I receive a notification, Android doesn't give me a popup at the top of my screen like in this example.
http://phandroid.s3.amazonaws.com/wp-content/uploads/2015/01/WhatsApp-Notifications.jpg

**Comment by rdelrosario** [comment]
Fixed on lastest NuGet version.

https://www.nuget.org/packages/Xam.Plugin.PushNotification
