### ISSUE TITLE
No resource found that matches the given name "...."

### ISSUE THREAD

**Issue by RosanaRufer** [rdelrosario/xamarin-plugins#3]
Hi, 
First of all, thank you for sharing this plugin. I've been following the instructions and got this error. Do you have any idea of what I'm missing?

![image](https://cloud.githubusercontent.com/assets/4906291/6439097/a94b5440-c0cf-11e4-8bb3-769fb4e15df9.png)

Added the NuGet Package to the shared project, iOS and Android.
Added initialization line in MainActivity and AppDelegate 
Minimum y Target Android version are set to Automatic
Xamarin.Forms version - is 1.3.5.6333 pre-1
Xamarin.Android.Support.v4 - updated to latest version
Xamarin.Android.Support.v7.AppCompat - updated to latest version
Xamarin.Android.Support.v7.MediaRouter - updated to latest version

**Comment by rdelrosario** [comment]
Hi,

What is the last android version you have installed on your Android SDK Manager?

Tried to reproduce but couldn't. Can you share a this project so i can look this issue closely?

Also make sure you have updated your Android SDK Manager libraries:

![image](https://cloud.githubusercontent.com/assets/2547751/6440604/1b0afb64-c0b5-11e4-93b8-c496e2bfa588.png)

**Comment by RosanaRufer** [comment]
**You've nailed it!** The Rev. number was different from my side but yeah. I started installing most recent packages like crazy and it finally compiled.

11 instead of 7 for Support Repository
22 instead for 20 for Google Play services ...etc

![screen shot 2015-03-02 at 15 11 28](https://cloud.githubusercontent.com/assets/4906291/6444167/22046e90-c0fc-11e4-805f-c56bd8935e89.png)

**Comment by rdelrosario** [comment]
Ok let me know when you test, if you run into any issues or everything works fine.

I guess i should include this on the documentation just in case happens to somebody else.

**Comment by rdelrosario** [comment]
Confirmame que no tuviste problemas al utilizarlo para así cerrar este issue. Te agregue en el README como colaboradora, agregue un TODO tambien para las cosas que están pendientes por si te interesa colaborar en esto, no tengo como probar en un dispositivo Windows Phone para probar por el momento, ni tengo mucha experiencia con Windows Phone por eso aun no lo he desarrollado.

**Comment by RosanaRufer** [comment]
Te confirmo que funcionó perfectamente en Android. Voy a probar en iOS (tengo que hacer toda la movida del provisioning profile otra vez porque mi manager se los cargó todos)
Con lo de Windows Phone puedo colaborar. Tengo 2 terminales WP y VisualStudio con Hyper-V

**Comment by RosanaRufer** [comment]
Rendy no podré confirmarte lo de iOS hoy, me han quitado los permisos del Apple Member Center. Puedes cerrar el issue porque de todas maneras el error era de Android sólamente.
Muchas gracias!

**Comment by rdelrosario** [comment]
No hay problema, iOS es todo un dolor de cabeza con eso de los certificados no se porque la complicaron tanto. Gracias por querer colaborar con lo de Windows & Windows Phone se aprecia :+1:
