### ISSUE TITLE
The setup link does not work!

### ISSUE THREAD

**Issue by TJProcessa** [rdelrosario/xamarin-plugins#36]
hi
The setup link does not work
*_Step by step instructions: [Adding Push Notification Post to your Xamarin Forms Application](http://web.archive.org/web/20150524090527/http://lemoncode.net/2015/04/17/adding-push-notifications-to-your-xamarin-forms-application-part-1/)
*_

**Comment by Knordy** [comment]
It does work, but here is another link to the same article:

https://lemoncoders.wordpress.com/2015/04/17/adding-push-notifications-to-your-xamarin-forms-application-part-1/
