### ISSUE TITLE
android: got token but unable to receive push

### ISSUE THREAD

**Issue by alexbleks** [rdelrosario/xamarin-plugins#40]
I do get a token but it won't receive push messages, any ideas?

**Comment by blocksninja** [comment]
Have you checked the result after sending the message?
During debug deployments I often find that I get "NotRegistered" during sending a message. This seems to be a problem after some debug-deployments. When I then Unregister() and Register() again you will receive a new token and it will work again.

**Comment by alexbleks** [comment]
By the way, should I use the whole token or parse out the colon?

Push Notification - Device Registered - Token : ckE6IdUYpdY:APA91bFiqlV-P9xEj2hqLJJI2NRgie-FUYql_8SWwH8R2H28nfZf6uFdMvsvXhQn5nFhKk65aDDSjEJaTjUjHfuvKOZ49aMIqPoYOMsXpuXkbZKOQSmikej70Tk7W5KTk6QYpc1ni8Cv

**Comment by blocksninja** [comment]
You should use the whole token.
From what I can remember the part before the colon didn't always exists, but you can just use the whole token.

**Comment by alexbleks** [comment]
I still can't receive messages but the server says OK.

Here is my android manifest:

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.coolapp.coolapp" android:versionCode="6">

<uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.WAKE_LOCK" />
  <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
  <permission android:name="com.coolapp.coolapp.gcm.permission.C2D_MESSAGE"
      android:protectionLevel="signature" />
  <uses-permission android:name="com.coolapp.coolapp.gcm.permission.C2D_MESSAGE" />

```
<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="21" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="android.permission.INTERNET" />
<meta-data android:name="com.google.android.maps.v2.API_KEY" android:value="<HIDDEN>" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.VIBRATE" />
<application android:icon="@drawable/icon" android:label="coolapp">
    <activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:theme="@android:style/Theme.Holo.Light" /> 
    <receiver
        android:name="com.coolapp.coolapp.GcmBroadcastReceiver"
        android:permission="com.google.android.c2dm.permission.SEND" >
        <intent-filter>
            <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            <category android:name="com.coolapp.coolapp.android.gcm" />
        </intent-filter>
    </receiver>
     android:name="com.coolapp.coolapp.GcmMessageHandler" />

</application>
```

</manifest>`

**Comment by rdelrosario** [comment]
@alexbleks Are you still having issues?
