### ISSUE TITLE
Doesn't even subscribe

### ISSUE THREAD

**Issue by kentcb** [rdelrosario/xamarin-plugins#44]
I'm at a loss as to how this could _ever_ work on Android. The `PushNotificationRegistrationIntentService` class defines a `SubscribeTopics` method, but nothing ever calls it! See [here](https://github.com/rdelrosario/xamarin-plugins/blob/master/PushNotification/PushNotification/PushNotification.Plugin.Android/PushNotificationRegistrationIntentService.cs#L60). Therefore, the client is never subscribed to any topic. :/

**Comment by rdelrosario** [comment]
It actually works without this change. But makes sense, will see if this has any impact on functionality.

**Comment by kentcb** [comment]
Can you explain _how_ it would work without a subscription? I assure you, I spent hours debugging through Android notifications yesterday and was simply unable to receive any notification without a subscription. Having said that, once I added the subscription I started receiving _two_ notifications. I've still not tracked down the cause, but it sure looks like a server issue, not client.

This would also explain #40.

**Comment by kentcb** [comment]
OK, I think I've figured this out and solved #46 at the same time (it's related). Will PR shortly.

**Comment by kentcb** [comment]
Note that I have solved #46 via #49. However, I was wrong about not requiring a subscription any more. A subscription is still required and I still don't understand how that could ever _not_ be the case.

**Comment by rdelrosario** [comment]
It really have worked fine without this change. I even made a sample a few months ago using Parse. But this sample could be use with any REST API:

https://github.com/CrossGeeks/Xamarin.Samples/tree/master/Xamarin.Android

**Comment by nsw2206** [comment]
I'm not getting any push notifications.
Have initialized in Main Activity, not as application class.
How do I try with Kents mods?
