### ISSUE TITLE
Receiving duplicate messages

### ISSUE THREAD

**Issue by kentcb** [rdelrosario/xamarin-plugins#46]
I haven't figured out why yet, but every message I send is received twice by `PushNotificationGcmListener`.

**Comment by kentcb** [comment]
The messages are delivered simultaneously on separate threads.

**Comment by kentcb** [comment]
What was happening was that without my own `receiver` and `intent-filter` in my manifest, I was not receiving _any_ notifications. But if I added one, it would also pick up the one defined by this library. Hence, I would get two notifications.

To fix this, I had to modify the registration attributes, which I am about to PR.

**Comment by rdelrosario** [comment]
You didn't need to set this on the manifest it worked without a receiver on the manifest.
