### ISSUE TITLE
cant install on android project incompatible version with mono.droid v2.2

### ISSUE THREAD

**Issue by jmeadecvlt** [rdelrosario/xamarin-plugins#5]
please help

**Comment by rdelrosario** [comment]
The plugin won't install in android v2.2 because uses Google Play Services. Will only be compatible from v2.3 up.

Reference:

http://android-developers.blogspot.com/2013/10/google-play-services-40.html?m=1

**Comment by rdelrosario** [comment]
Do you need to run your project in Froyo v2.2?
