### ISSUE TITLE
Device Motion Plugin nuget package

### ISSUE THREAD

**Issue by steevelefort** [rdelrosario/xamarin-plugins#53]
Hi,

The nuget package requires nuget version 2.81 (2.8.1 ?) and can't be used on Xamarin Studio / osX :
The 'Xam.Plugin.DeviceMotion 1.1.1' package requires NuGet client version '2.81' or above, but the current NuGet version is '2.8.7.0'.

Regards

**Comment by rdelrosario** [comment]
Fixed. Thanks for reporting. Updated package should be available in a few hours

**Comment by steevelefort** [comment]
Thanks !
