### ISSUE TITLE
Still working

### ISSUE THREAD

**Issue by markobls** [rdelrosario/xamarin-plugins#56]
I need to implement push notification,
I'm using Azure Messaging client with GcmClient, but im having some problems, like the app crash when receive notification while app is open.

So, i need to find another solution, is your still working ?

**Comment by rdelrosario** [comment]
Is working. What is the stacktrace of tour crash?

**Comment by markobls** [comment]
I solved it now after 2 days ago.

I needed to add GcmReceiver in manifest.

Thanks anyways.
