### ISSUE TITLE
Service stopped sometimes

### ISSUE THREAD

**Issue by mariusmuntean** [rdelrosario/xamarin-plugins#62]
Hi,

When my app is in foreground and I force-stop it (in the app switcher I swipe left/right) the Intent service is sometimes also stoppen and then I don't get anymore push notifications.

Would it be possible to allow the users of the plugin providing custom implementations of the service such that I could detect when the service is stopped and then immediately restart it (based on some logic).

Cheers,
Marius

**Comment by rdelrosario** [comment]
Actually you can use any service, plugin provides one but you can use your on instead. The main thing is that should be started in the Application class.
