### ISSUE TITLE
FormatException in catch block(s)

### ISSUE THREAD

**Issue by jacobslusser** [rdelrosario/xamarin-plugins#69]
I noticed a bug in the catch blocks of PushNotification.Plugin.Android/PushNotificationImplementation.cs. I had forgotten to add the `com.google.android.c2dm.permission.RECEIVE` permission which caused an exception during registration. In the catch block for `Register` the exception is concatenated with the format string. That's usually not an issue, but if the exception message contains `"{...}"` then it will result in a `FormatException`.

``` cs
catch (System.Exception ex)
{
    System.Diagnostics.Debug.WriteLine(string.Format("{0} - Error :" + ex.Message, Tag));

    CrossPushNotification.PushNotificationListener.OnError(string.Format("{0} - Register - " + ex.ToString(), Tag), DeviceType.Android);

}
```

The sample exception message that caused the `catch` block to execute:

```
Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
```

This caused the original exception to get swallowed and took me a while to figure out that my issue was a missing permission rather than the `FormatException` reported.

The same bug can be found in the `Unregister` method and perhaps other places in the component.

Otherwise, the component has done everything else as advertised. Thanks.

**Comment by rdelrosario** [comment]
Let me know if this is fixed on 1.2.3 version
