### ISSUE TITLE
Set Title and Text Complex JObject

### ISSUE THREAD

**Issue by leo-mck** [rdelrosario/xamarin-plugins#74]
Hi, thank you for your amazing work!
I receive an object like this from the server:

`{{
  "to": "xyz",
  "notification": {
    "title": "my title",
    "body": "body text"
  },
  "collapse_key": "do_not_collapse"
}}`

I tried to configure like this: `CrossPushNotification.NotificationContentTitleKey = "title";` and like this: `CrossPushNotification.NotificationContentTitleKey = "notification.title";` but neither work. Is it possible or should I simplify my JObject?

**Comment by rdelrosario** [comment]
Set NotificationContentDataKey  to "notification"
