### ISSUE TITLE
Push Notification: Android version confusion

### ISSUE THREAD

**Issue by skrichten** [rdelrosario/xamarin-plugins#75]
In the readme, the Platform Support table says "API 14+" for Android.

Then under the Android Specifics section it says...
"Must compile against 21 as plugin is using API 21 specific things."

These statements seem to contradict each other, but I'm new to mobile dev, so maybe I am missing something?

**Comment by rdelrosario** [comment]
API 14+ refers to the  minimumSdkVersion but target should be API 21

**Comment by SimoneMSR** [comment]
What should one do in order to use the library for API 21 and above (+21) ?

**Comment by rdelrosario** [comment]
It can run with minimum version 16+ but target should be at least 21+
