### ISSUE TITLE
Android: Get token, but unable to receive after update

### ISSUE THREAD

**Issue by alexbleks** [rdelrosario/xamarin-plugins#77]
Hello! After I just updated to latest Xamarin and Xam.Plugin.PushNotification I cannot receive push messages on android anymore, however it does register with a token

**Comment by alexbleks** [comment]
UPDATE; It works for a few hours, then it stops and I have to reinstall the whole app to get it working again.

**Comment by rdelrosario** [comment]
Is a Release or Debug Build?

**Comment by alexbleks** [comment]
This is a release build.

**Comment by rdelrosario** [comment]
Just released a new version. Let me know if still getting the issue on the newest version.
