### ISSUE TITLE
Problema in Xamarin.Forms project for Android

### ISSUE THREAD

**Issue by homerokzam** [rdelrosario/xamarin-plugins#9]
I'm having the following problem in an XForms project for Android: Push notification error - CrossPushNotification - Register - Java.IO.IOException: Exception of type 'Java.IO.IOException' was thrown.

In this project that is working for iOS I use PushSharp on my server.

**Comment by rdelrosario** [comment]
Seems to be a networking issue. Where are you calling the register method?

**Comment by homerokzam** [comment]
I call the method in the class:

public partial class App: Application
{
...
     protected override void OnStart ()
     {
       // Handle When your app starts
       CrossPushNotification.Current.Register ();
     }
...
}

But then event CrossPushNotificationListener. OnRegistered (IPushNotificationListener) does not fire.

**Comment by rdelrosario** [comment]
Have you initialized the plugin?

**Comment by homerokzam** [comment]
Yes. I do the method CrossPushNotification.Initialize<CrossPushNotificationListener>("") in MainActivity.cs of the Android project. And I do the method CrossPushNotification.Current.Register() in OnStart event of the PCL project (App.cs).

**Comment by rdelrosario** [comment]
Did you get working?

**Comment by homerokzam** [comment]
No, I didn't. Works with iOS, but with Android not.

**Comment by homerokzam** [comment]
rdelrosario, I discovered the error. The problem is that in the Android application, OnRegistered event triggers only on the first application running on the device. After the first run the event does not fire. Not that it's a problem, but I did not foresee this.

Thank you.

**Comment by rdrokkralabs** [comment]
Yes it prevents multiple time registration. Why you will like to register it if it's already registered?

**Comment by homerokzam** [comment]
I think this may be a mistake. IOS project this event is triggered every time the application starts. The Token value on evento OnRegistered for Android seems to me what's wrong. Do you have an example using the plugin for Android?

**Comment by rdelrosario** [comment]
I will fix this for iOS, so it triggers just one time because shouldn't be registering each time.

**Comment by shanthuk** [comment]
I am using visual studio 2015 and XF 2.0. After adding these packages related to notification plugin to my solution, android application fails to deploy onto device (iOS is working properly). Any idea what might be causing this?

**Comment by rdelrosario** [comment]
What error are you getting?

**Comment by shanthuk** [comment]
Strangely there are no errors. In the output window I see the following message
check to make sure that in your build configuration build and deploy both are checked (not exactly the same text, but semantically that is what it says).
Hope this helps.
I though I had enable some of the device permissions (such as INTERNET etc.). I tried to enable quite a few options. Still it was failing to deploy.

I wanted to be sure. As soon as I removed these nuget packages, I was able to deploy my application to device again.

I really liked the idea of abstracting all the notification stuff in a PCL. Let me know if I can be of any help. If needed, I can setup a remote goto meeting for you to look at.

**Comment by rdelrosario** [comment]
Ok here is my skype: rendyleonel

**Comment by jwood803** [comment]
I concur about a sample project on the best way to implement everything. Not exactly sure how this all should work with Android.

**Comment by jwood803** [comment]
I think [this is the updated link](https://lemoncoders.wordpress.com/2015/04/17/adding-push-notifications-to-your-xamarin-forms-application-part-1) from above.

Though, I'm still confused on how to implement in Android to receive the device token and when a message is received. Looking at part two from the link, it still doesn't seem to show that.
