### ISSUE TITLE
Problem with intent filters

### ISSUE THREAD

**Issue by tanis2000** [rdelrosario/xamarin-plugins#97]
I just noticed that you have this line of code where you define an IntentFilter for a sample package name:

https://github.com/rdelrosario/xamarin-plugins/blob/master/PushNotification/PushNotification/PushNotification.Plugin.Android/AppUpdateReceiver.cs#L15

When Xamarin compiles the application using this library, it adds that filter to the manifest with that fake package name. I noticed that you cannot override that attribute because IntentFilters can be defined more than once per class, so it would just try to add one more intent filter resulting in a malformed manifest.

Are you aware of any way to remove an IntentFilter from the hosting project or could you just remove that line and release an updated version of this library eventually?

Cheers!

**Comment by rdelrosario** [comment]
just removed this line on latest prerelease: https://www.nuget.org/packages/Xam.Plugin.PushNotification/1.2.5-beta
