### ISSUE TITLE
App Android stop when receives Push

### ISSUE THREAD

**Issue by ejastre** [rdelrosario/xamarin-plugins#99]
If the app is open the push works and opens, but if it has been terminated when a push arrives the app breaks. I installed via Nuget in Xamarin Forms version 1.2.4. I tested both in Debug and Release. Any solution?

**Comment by JulianPasque** [comment]
I am facing the same problem.

**Comment by jgoelten** [comment]
I can see the same behaviour in my app.

Update: After using the attached PushNotificationAppStarter class that was included when installing the nuget package, the intent service successfully handles notification when the app is terminated.

**Comment by jorgenstorlie** [comment]
me to, updated version does not compile with latest version of GooglePlayServices (version 32.961)

**Comment by lucascc26** [comment]
@jgoelten can you provide a sample project that is working?
It's been a nightmare, I've tried a lot of things but I still can't receive notifications if my app is closed.

Thanks.

**Comment by ejastre** [comment]
[SOLVED] To solved this issue, just follow the steps in this link: https://github.com/rdelrosario/xamarin-plugins/tree/master/PushNotification

Android

On the Android Application class, is better to use the OnCreate of the Android Application class so you can handle push notifications even when activities are closed or app not running by using our PushNotificationService to keep listening to push notifications.

But is that not a requirement you could do initialization on your MainActivity class
